---
name: Internal - Common Continuous Integration tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  workshop-ci:
    name: Workshop CI
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Skip linting for workshop
        run: echo "Linting is disabled in this workshop snapshot."
